#!/usr/bin/env node
/**
 * Fetch all WordPress blog data and write it into lib/blog-cache.js
 * so the Next.js static export can build without a live API connection.
 *
 * Usage:  npm run cache-blog          (or: node scripts/cache-blog.mjs)
 * Then:   git add lib/blog-cache.js && git commit -m "Update blog cache" && git push
 */

const WP_API =
  'https://blog.p5marketing.com/wp-json/wp/v2';

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CACHE_PATH = resolve(__dirname, '..', 'lib', 'blog-cache.js');

async function wpFetch(endpoint) {
  const res = await fetch(`${WP_API}/${endpoint}`, {
    headers: { 'User-Agent': 'P5Marketing-CacheBuild/1.0' },
  });
  if (!res.ok) throw new Error(`${endpoint}: ${res.status} ${res.statusText}`);
  return res.json();
}

async function main() {
  console.log('Fetching posts from WordPress...');
  const posts = await wpFetch('posts?per_page=100&_embed=true&orderby=date&order=desc');
  console.log(`  -> ${posts.length} post(s)`);

  console.log('Fetching categories...');
  const categories = await wpFetch('categories?per_page=100&hide_empty=true');
  console.log(`  -> ${categories.length} category/ies`);

  const slugs = posts.map((p) => p.slug);

  const js = `/**
 * Static blog-data cache.
 *
 * AUTO-GENERATED by scripts/cache-blog.mjs — do not edit by hand.
 * Last updated: ${new Date().toISOString()}
 *
 * To refresh after publishing a new post, run locally:
 *   npm run cache-blog
 */

/* eslint-disable */

export const CACHED_POSTS = ${JSON.stringify(posts, null, 2)};

export const CACHED_CATEGORIES = ${JSON.stringify(categories, null, 2)};

export const KNOWN_SLUGS = ${JSON.stringify(slugs, null, 2)};
`;

  writeFileSync(CACHE_PATH, js, 'utf-8');
  console.log(`\nCache written to lib/blog-cache.js (${slugs.length} post(s))`);
  console.log('Now commit and push to update Vercel.');
}

main().catch((err) => {
  console.error('Cache build failed:', err.message);
  process.exit(1);
});
